version: "3"

services:
  backend:
    build: ./backend
    image: backend
    container_name: backend_container
    links:
      - mysql
    ports:
      - "3031:3031"
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./backend/python:/var/www/

  frontend:
    build: ./frontend
    image: frontend
    container_name: frontend_container
    links:
      - backend
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./web/vue/dist:/home/www/contents

  mysql:
    image: mysql:5.7
    container_name: mysql_container
    volumes:
      - ./mysql/work:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 33066:3306
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root